const BUDDY_DATA = [
    { name: "Quill McGee",          fact: "Once wrote an entire novel in invisible ink by accident." },
    { name: "Blot Bramblewick",     fact: "Believes semicolons are just tired colons." },
    { name: "Inksworth Toadle",     fact: "Has never read the ending of any book they've started." },
    { name: "Scribble Fern",        fact: "Types exclusively with their left pinky finger." },
    { name: "Parchment Pete",       fact: "Once confused a thesaurus for a dinosaur book. Was not disappointed." },
    { name: "Draft Dodger Dan",     fact: "Has 47 unfinished chapter ones." },
    { name: "Plotsy McPlotface",    fact: "Names all characters 'Dave' until the final draft." },
    { name: "Comma Clementine",     fact: "Adds commas to everything, including, soup." },
    { name: "Ellipsis Eddie",       fact: "Never finishes a sent..." },
    { name: "Margot Marginalia",    fact: "Writes more notes in the margins than in the actual document." },
    { name: "Footnote Freddy",      fact: "Communicates exclusively in footnotes.¹" },
    { name: "Chapter Chuck",        fact: "Refuses to read chapter two of anything. 'Chapter one is enough,' he says." },
    { name: "Synopsis Sally",       fact: "Has synopsised every conversation she's had since 2019." },
    { name: "Adverb Andy",          fact: "Speaks very loudly, extremely slowly, and thoroughly annoyingly." },
    { name: "Passive Vera",         fact: "Mistakes were made, by her, often." },
    { name: "Foreshadow Phil",      fact: "Constantly hints something big is coming. It never does." },
    { name: "Backstory Bertha",     fact: "Cannot introduce herself without going back three generations." },
    { name: "Cliché Claude",        fact: "Every word he says has been said a thousand times before, like rain on a summer's day." },
    { name: "Metaphor Mildred",     fact: "Life, to her, is a metaphor for something she can't quite put her finger on." },
    { name: "Red Herring Rhonda",   fact: "Always seems suspicious. Is never relevant." },
    { name: "Deus Rex",             fact: "Solves all problems by appearing out of nowhere." },
    { name: "Subplot Stan",         fact: "Has seventeen ongoing personal storylines, none of which have resolved." },
    { name: "MacGuffin Mo",         fact: "Very important. Nobody knows why." },
    { name: "Chekhov's Charlie",    fact: "If he appears in chapter one, he will definitely cause problems later." },
    { name: "Cliffhanger Harriet",  fact: "Always leaves conversations at the most dramatic mome—" },
    { name: "Protagonist Pat",      fact: "Refuses to be anyone's sidekick." },
    { name: "Antagonist Agnes",     fact: "Not evil. Just very misunderstood and extremely inconvenient." },
    { name: "Unreliable Ned",       fact: "Swears everything he says is absolutely true." },
    { name: "Narrator Norma",       fact: "Knows more than she's letting on." },
    { name: "Epilogue Earl",        fact: "Always shows up after everything is already over." },
    { name: "Penelope Plothole",    fact: "Has never noticed a single inconsistency in anything, ever." },
    { name: "Revision Rex",         fact: "Currently on draft forty-seven of his shopping list." },
    { name: "Deadline Dolores",     fact: "Hasn't met a deadline since the late 1990s." },
    { name: "Procrastination Percy",fact: "Plans to start writing tomorrow. Has been planning this since 2008." },
    { name: "Exposition Eloise",    fact: "As you know, Bob, she explains everything at unnecessary length." },
    { name: "Flashback Frankie",    fact: "Cannot have a conversation without going back to what happened in 2003." },
    { name: "Foreshadow Florence",  fact: "Wears a dark coat. The darkest coat you'll ever see. Remember that." },
    { name: "Denouement Denny",     fact: "Wraps everything up a bit too neatly." },
    { name: "Climax Karl",          fact: "Everything he does is the most important thing that has ever happened." },
    { name: "Rising Action Rita",   fact: "Has been building to something for eleven years." },
    { name: "Falling Action Fred",  fact: "Things are winding down. Slowly. Very slowly." },
    { name: "Resolution Robin",     fact: "Fixes things. Usually the wrong things." },
    { name: "Theme Theodore",       fact: "Everything he does means something. He finds this exhausting." },
    { name: "Motif Morris",         fact: "Keeps showing up. You'll understand why eventually." },
    { name: "Symbol Simon",         fact: "Is definitely not just a chair. He represents something." },
    { name: "Allegory Alice",       fact: "On the surface she seems perfectly normal. She is not normal." },
    { name: "Irony Ivan",           fact: "Genuinely surprised every time the unexpected happens." },
    { name: "Sarcasm Sam",          fact: "Oh sure, editing is really fun. Love it. Very enjoyable." },
    { name: "Hyperbole Helen",      fact: "Has literally done everything a million times." },
    { name: "Understatement Uma",   fact: "Things are, she supposes, slightly on fire." },
    { name: "Soliloquy Sol",        fact: "Often speaks at great length when alone. And when not alone." },
    { name: "Monologue Mo",         fact: "Once talked for four hours about bread." },
    { name: "Dialogue Dot",         fact: "Cannot have a conversation without it feeling oddly scripted." },
    { name: "Aside Aisling",        fact: "Has opinions about everything she keeps almost sharing." },
    { name: "Chorus Charlie",       fact: "Repeats important things. Repeats important things." },
    { name: "Prologue Pearl",       fact: "Always appears before things have really started." },
    { name: "Interlude Iris",       fact: "Pops up unexpectedly with something only loosely related." },
    { name: "Act Break Betty",      fact: "Disappears for long periods, usually at the worst possible time." },
    { name: "Stage Direction Sid",  fact: "Narrates exactly what he's doing as he does it. (He picks up the cup.)" },
    { name: "Inkblot Iggy",         fact: "Found a Rorschach test and saw nothing but plot diagrams." },
    { name: "Pendragon Smudge",     fact: "Claims to have once written a haiku by sneezing." },
    { name: "Serif Stan",           fact: "Gets into arguments about fonts at parties." },
    { name: "Helvetica Hank",       fact: "Believes all of the world's problems could be solved with better typography." },
    { name: "Kerning Karen",        fact: "Deeply uncomfortable with anything too close together." },
    { name: "Orphan Oliver",        fact: "Always ends up alone at the bottom of the page." },
    { name: "Widow Winnie",         fact: "Left dangling at the top with no support." },
    { name: "Gutter Gary",          fact: "Lives between chapters. It's fine. He's used to it." },
    { name: "Bleed Benny",          fact: "Goes slightly beyond the margins. On purpose." },
    { name: "Leading Larry",        fact: "Always leaves a little extra space between things." },
    { name: "Tracking Trudy",       fact: "Monitors the spacing of everything she does, meticulously." },
    { name: "Recto Reg",            fact: "Only exists on the right side of things. Philosophically too." },
    { name: "Verso Vera",           fact: "Prefers the left. Has very strong feelings about this." },
    { name: "Colophon Colin",       fact: "Only appears at the very end, to take credit." },
    { name: "Errata Erica",         fact: "List of known errors: too long to print." },
    { name: "Index Igor",           fact: "Has memorised the page number of everything he's ever encountered." },
    { name: "Appendix April",       fact: "Contains information that didn't quite fit anywhere else in her life." },
    { name: "Glossary Glen",        fact: "Defines terms nobody asked about." },
    { name: "Bibliography Bob",     fact: "Can cite the source of any claim he has ever made." },
    { name: "Citation Celia",       fact: "Always has a reference. Always (Smith, 2024)." },
    { name: "Peer Review Pru",      fact: "Has opinions about your work. You didn't ask. She'll tell you anyway." },
    { name: "First Edition Freddy", fact: "Rare. Possibly valuable. Definitely smells funny." },
    { name: "Paperback Paula",      fact: "Cheaper than she appears. Doesn't mind one bit." },
    { name: "Hardcover Harriet",    fact: "Takes up more space but lasts much longer. Her own description." },
    { name: "Dust Jacket Derek",    fact: "Primarily decorative. Occasionally protective." },
    { name: "Bookmark Bonnie",      fact: "Loses her place constantly, despite literally being a bookmark." },
    { name: "Dog-ear Doug",         fact: "Does not believe in bookmarks. Considered a villain in some circles." },
    { name: "Spine Sylvia",         fact: "Holds everything together. Nobody notices until she's gone." },
    { name: "Endpaper Edna",        fact: "Found at both the beginning and the end. Confused about her role." },
    { name: "Chapter Heading Chad", fact: "Bold. Slightly larger than everyone else. Absolutely knows it." },
    { name: "Pull Quote Quinn",     fact: "Takes things out of context. Looks great doing it." },
    { name: "Typeface Tessa",       fact: "Has 2,000 fonts installed. Uses Times New Roman." },
    { name: "Justified Jim",        fact: "Everything he does is exactly aligned. He cannot explain why." },
    { name: "Ragged Right Roger",   fact: "Refuses to conform to any margin on his right side." },
    { name: "Drop Cap Daphne",      fact: "Makes a grand entrance. Every single time." },
    { name: "Running Head Rita",    fact: "Appears at the top of every page. Tiring, but dedicated." },
    { name: "Catchword Catherine",  fact: "Repeats the first word of the next page at the bottom of this one. Old habit." },
    { name: "Ligature Lily",        fact: "Connects letters that work well together. A matchmaker of sorts." },
    { name: "Dingbat Dennis",       fact: "Decorative. Eccentric. Often used as a section break. ✦" },
    { name: "En Dash Emma",         fact: "Shorter than expected but works harder than you'd think." },
    { name: "Em Dash Emmett",       fact: "Shows up mid-sentence—unexpectedly—and always makes a point of it." },
    { name: "Oxford Comma Olive",   fact: "Insists on being included. Causes arguments at every dinner party." },
    { name: "Interrobang Iggy",     fact: "Is that not the most exciting thing you've ever heard?!" },
    { name: "Ampersand Amos",       fact: "Prefers to be with others & rarely travels alone." },
];
