export const CONFIG = {
    inspiration: [
        "NEURAL SPIKE: A character just lied. Why?",
        "NEURAL SPIKE: Describe the smell of the current room.",
        "NEURAL SPIKE: Next sentence must be exactly 7 words.",
        "NEURAL SPIKE: A minor character reveals a hidden weapon/item.",
        "NEURAL SPIKE: Kill the lighting in the scene. What happens?",
        "NEURAL SPIKE: The protagonist hears a sound from the floor above.",
        "NEURAL SPIKE: A character's internal monologue contradicts their words."
    ],
    checkpoints: [
        { pct: 0,    name: "Opening Image (1)", tasks: ["Visual snapshot of status quo", "Establish tone/scope"] },
        { pct: 1.25, name: "Opening Image (2)", tasks: ["The hero’s world in stasis", "Show the 'Internal Lack'"] },
        { pct: 2.5,  name: "Theme Stated", tasks: ["Side character mentions the lesson", "Hint at the life-changing truth"] },
        { pct: 3.75, name: "Setup: Part 1", tasks: ["Introduce A-Story cast", "Show 'Save the Cat' moment"] },
        { pct: 5,    name: "Setup: Part 2", tasks: ["Establish 'Stasis = Death'", "Show physical obstacles"] },
        { pct: 6.25, name: "Setup: Part 3", tasks: ["Define the hero's 'Want'", "The boring routine in detail"] },
        { pct: 7.5,  name: "Setup: Part 4", tasks: ["Introduce primary antagonist", "The world starts to crack"] },
        { pct: 10,   name: "The Catalyst", tasks: ["The life-changing event", "The knock on the door"] },
        { pct: 12.5, name: "The Debate: (1)", tasks: ["The 'Refusal of the Call'", "Initial fear of the unknown"] },
        { pct: 15,   name: "The Debate: (2)", tasks: ["Doubts about ability", "Seeking advice from mentors"] },
        { pct: 17.5, name: "The Debate: (3)", tasks: ["Evaluating risks of staying", "Pressure builds to leave"] },
        { pct: 20,   name: "The Debate: (4)", tasks: ["Gathering resources", "Internal decision made"] },
        { pct: 22.5, name: "The Decision", tasks: ["Final look at the old world", "Saying goodbye to stasis"] },
        { pct: 25,   name: "Break Into Two", tasks: ["Proactive choice to cross", "Transition to Act 2"] },
        { pct: 26.5, name: "B Story: Part 1", tasks: ["Introduce B-Story character", "The thematic mirror appears"] },
        { pct: 28,   name: "B Story: Part 2", tasks: ["First B-Story interaction", "A-plot vs B-plot contrast"] },
        { pct: 30,   name: "Fun & Games (1)", tasks: ["Exploration of 'Upside Down' world", "Lighthearted trials"] },
        { pct: 32.5, name: "Fun & Games (2)", tasks: ["The 'Hook' in action", "Promise of the Premise"] },
        { pct: 35,   name: "Fun & Games (3)", tasks: ["Hero gains small victory", "New skills tested"] },
        { pct: 37.5, name: "Fun & Games (4)", tasks: ["Secondary character subplots", "Hero starts to feel safe"] },
        { pct: 40,   name: "Fun & Games (5)", tasks: ["Overconfidence mistake", "Antagonist reacts"] },
        { pct: 42.5, name: "Fun & Games (6)", tasks: ["A and B plots weave", "Pressure begins to simmer"] },
        { pct: 45,   name: "Approaching Mid", tasks: ["Plan for 'Big Goal' set", "Temporary alliance"] },
        { pct: 47.5, name: "Midpoint Shift", tasks: ["Stakes raised unexpectedly", "Turning proactive"] },
        { pct: 50,   name: "The Midpoint", tasks: ["False Victory or Defeat", "No Turning Back moment"] },
        { pct: 52.5, name: "Bad Guys Close (1)", tasks: ["Antagonist regroups", "Internal flaws resurface"] },
        { pct: 55,   name: "Bad Guys Close (2)", tasks: ["The 'Noose Tightens'", "Support systems fail"] },
        { pct: 57.5, name: "Bad Guys Close (3)", tasks: ["Loss of minor ally", "Plan starts to crumble"] },
        { pct: 60,   name: "Bad Guys Close (4)", tasks: ["Team paranoia/doubt", "Physical danger escalates"] },
        { pct: 62.5, name: "Bad Guys Close (5)", tasks: ["The 'Secret' revealed", "Past catches up"] },
        { pct: 65,   name: "Bad Guys Close (6)", tasks: ["Hero backed into corner", "Betrayal from ally"] },
        { pct: 67.5, name: "Bad Guys Close (7)", tasks: ["Bad Guys in the house", "Total loss of control"] },
        { pct: 70,   name: "Bad Guys Close (8)", tasks: ["Final resource spent", "Despair sets in"] },
        { pct: 75,   name: "All Is Lost", tasks: ["The Whiff of Death", "Hero loses everything"] },
        { pct: 77.5, name: "Dark Night (1)", tasks: ["Wallowing in defeat", "Hero is truly alone"] },
        { pct: 80,   name: "Dark Night (2)", tasks: ["Hero admits flaw", "The 'Aha!' moment"] },
        { pct: 82.5, name: "Dark Night (3)", tasks: ["Synthesizing lessons", "New plan formed"] },
        { pct: 85,   name: "Break Into Three", tasks: ["Rising from the ashes", "Choosing to fight"] },
        { pct: 90,   name: "The Finale", tasks: ["Storming the Castle", "The Climax"] },
        { pct: 100,  name: "Final Image", tasks: ["The hero is changed", "Mirror of Opening Image"] }
    ],
    genreBosses: {
        fantasy: ["Empty Parchment", "Prophecy's Whisper", "Boring Village", "Dragon's Raid", "Crossroad Spirit", "The Gatekeeper", "Mysterious Rogue", "Enchanted Forest", "Mirror of Reversal", "Orc Battalion", "Shattered Sword", "Mourning Woods", "Ancient Forge", "Shadow Architect", "Golden Throne", "Wandering Knight", "Spore Caves", "Griffin's Nest", "The Alchemist", "Hidden Map", "Siren's Song", "Stone Troll", "Forgotten Rune", "Iron Keep", "Wizard's Tower", "The Dark Elf", "Poisoned Well", "Siege Engine", "The Wyvern", "Cursed King", "Dragon's Lair", "Obsidian Gate", "Inner Demon", "The Phoenix", "Great Spirit", "Final Stand", "Sword of Light", "Shadow Lord", "Victory Feast", "New Legend"],
        sciFi: ["Offline Console", "AI's Warning", "Rusty Outpost", "Distress Signal", "Navigation Error", "Rogue Protocol", "Alien Diplomat", "Asteroid Field", "Event Horizon", "System Virus", "Oxygen Leak", "Cold Vacuum", "Hard Reboot", "Galactic Overlord", "The Supernova", "Cryo Chamber", "Junk Trader", "Moon Base", "The Wormhole", "Star Charter", "Android Spy", "Nebula Cloud", "Gravity Well", "Ion Storm", "Plasma Core", "Black Hole", "Dyson Sphere", "Warp Drive", "Hive Mind", "Orbital Cannon", "The Mothership", "The Pulsar", "Singularity", "Solar Flare", "Time Rift", "Binary Star", "The Void", "Omega Code", "Galactic Peace", "New Frontier"],
        urbanFantasy: ["Dusty Cafe", "Static Air", "Strange Tattoo", "Hidden Sigil", "Alleyway Shadow", "Coded Lamp", "Grumpy Landlord", "Veil Flicker", "Council Letter", "First Brawl", "Unseen Wall", "Silver Hand", "Cryptic Text", "Familiar Spirit", "Night Market", "Guard Dog", "Golem Sentry", "Ley Line Surge", "Vampire Enforcer", "Shifter Mob", "Syndicate Boss", "Corrupt Mage", "Memory Thief", "Ghostly Echo", "Cursed Object", "Hidden Library", "Double Agent", "Sanctuary Breach", "Waning Moon", "Ritual Site", "Blood Pact", "Dark Covenant", "Inner Demon", "Shattered Staff", "Midnight Hour", "Last Candle", "Spell of Awakening", "City's Guardian", "Dawn Bringer", "Awakened City"],
        thriller: ["Quiet Morning", "Ominous Note", "Growing Suspicion", "First Attack", "Phone Call", "No Return", "Unexpected Ally", "High Speed Chase", "The Tracker", "Safehouse Breach", "The Mole", "Total Isolation", "The Trap", "Mastermind", "The Escape", "The Set-up", "Shadow Agency", "Encryption Key", "Double Cross", "Extraction", "Network Blackout", "Target Locked", "Deep Fake", "Cover Blown", "Safe Deposit Box", "The Hitman", "Interrogation", "The Ransom", "Ticking Clock", "Point Blank", "Ransom Note", "The Leverage", "Broken Protocol", "The Fall Guy", "Last Stand", "Confrontation", "The Reveal", "Justice Served", "Aftermath", "Case Closed"],
        horror: ["Peaceful House", "Cold Spot", "Local Legend", "First Scream", "Warning Ignored", "Locked Door", "Creeping Shadow", "False Security", "The Ritual", "Entity Revealed", "Bloody Grudge", "Darkest Night", "Ancient Evil", "The Basement", "The Attic", "Broken Mirror", "Static TV", "Ouija Board", "Shadow Figure", "Blood Writing", "The Possession", "Isolated Cabin", "Full Moon", "The Crypt", "Cemetery Gates", "The Cult", "Sacrificial Knife", "The Curse", "Urban Legend", "The Screaming", "Dark Woods", "The Fog", "Nightmare Fuel", "Final Girl", "The Survivor", "Daylight Breaks", "The Burial", "Unanswered Phone", "The Haunting", "The End?"],
        romance: ["Lonely Studio", "Friend's Advice", "Predictable Life", "Chance Encounter", "Panic Attack", "First Date", "Quirky Rival", "Honeymoon Phase", "Big Secret", "Ex's Return", "Heartbreak Engine", "Tearful Rainstorm", "Grand Gesture", "Wall of Pride", "Wedding Bells", "Awkward Hello", "Coffee Date", "Shared Umbrella", "Misread Text", "Secret Admirer", "First Kiss", "Public Scene", "Family Dinner", "Old Flame", "Misunderstanding", "Long Distance", "The Jealousy", "Compromise", "Second Chance", "The Proposal", "Love Letter", "Midnight Dance", "Sunset Walk", "Forgiveness", "The Soulmate", "Anniversary", "Happy Ever After", "New Beginning", "Forever Home", "True Love"],
        crime: ["Cold Case", "Partner's Hunch", "Routine Patrol", "Murder Scene", "Corrupt Captain", "First Interrogation", "Shady Informant", "Paper Trail", "Double Cross", "Syndicate Enforcers", "Framed Evidence", "Prison Cell", "Missing Link", "Kingpin", "Handcuffs", "Police Lineup", "Evidence Locker", "Crime Lab", "Witness Room", "District Attorney", "Search Warrant", "Stakeout", "Getaway Car", "Safe House", "Undercover Job", "The Payoff", "The Snitch", "The Smuggler", "The Heist", "The Ransom", "Police Siren", "The Courtroom", "The Jury", "The Verdict", "The Sentence", "The Parole", "Redemption", "Clean Slate", "New Life", "Justice Done"]
    }
};
